In [1]:
import numpy as np

In [2]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print('arg_max', arr.argmax())
# write code here to print the row + col number?
row = arr.argmax() //  arr.shape[1]
col = arr.argmax() % arr.shape[1]
print('row:', row)
print('col:', col)
print('max value:', arr[row, col])
print(f"({row},{col})")
print(arr.argmax() % arr.shape[1])


[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arg_max 11
row: 2
col: 1
max value: 99
(2,1)
1


In [3]:
# Topic 05 of 09
# Array Properties & Info

In [4]:
# Q1
# Given c = np.ones((2, 3, 4)) — what does c.ndim return?

c = np.ones((2, 3, 4))
print(c.ndim)

3


In [5]:
# Q2
# Given b = np.zeros((4, 3)) — what does len(b) return?

b = np.zeros((4, 3))
print(len(b))

4


In [6]:
# Q3
# Given d = np.arange(12).reshape(3,4) — what does d.size return?

d = np.arange(12).reshape(3,4)
print(d.size)

12


In [7]:
# Q4
# Given a = np.array([[1,2,3],[4,5,6]]) — what does a.shape return?

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [8]:
# Q5
# Given e = np.array([1.0, 2.0, 3.0]) — what does e.dtype return?

e = np.array([1.0, 2.0, 3.0])
print(e.dtype)

float64


In [9]:
# Q6
# Given f = np.array([1, 2, 3]) — what does f.astype(float) produce?

f = np.array([1, 2, 3])
print(f.astype(float))

[1. 2. 3.]


In [11]:
sigmoid = lambda x: 1 / (1 + np.exp(-x))
print(f'sigmoid {sigmoid}')

np.sin(np.array([0, np.pi/2, np.pi]))
np.tan(np.array([0, np.pi/2, np.pi]))

sigmoid <function <lambda> at 0x000002072A926160>


array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [12]:
# Topic 06 of 09
# Arithmetic Operations

In [13]:
# Question 1
# Given a = np.array([1, np.e, np.e**2]) — what does np.log(a) return?
# natural log:  
# ln(1)=0
# ln(e)=1
# ln(e²)=2
# array([?, ?, ?])

a = np.array([1, np.e, np.e**2])
np.log(a) # returns [0, 1, 2] because that is the natural log for each of the numbers in the array

array([0., 1., 2.])

In [14]:
# Question 2
# Given a = np.array([10, 20, 30]) and b = np.array([1, 2, 3]) — what does np.subtract(a, b) return?
# array([?, ?, ?])

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
np.subtract(a, b) # returns the numbers in array a minus the numbers in array b, giving [9, 18, 27]

array([ 9, 18, 27])

In [15]:
# Question 3
# Given a = np.array([0, 1, 2]) — what does np.exp(a) return? (round to 2 dp)
# e⁰=1
# e¹≈2.72
# e²≈7.39
# array([?, ?, ?])

a = np.array([0, 1, 2])
np.exp(a) # returns [1, 2.72, 7.39], the value of e^x for each number x in the array

array([1.        , 2.71828183, 7.3890561 ])

In [16]:
# Question 4
# Given A = np.array([[1,2],[3,4]]) and B = np.array([[1,0],[0,1]]) — what does A.dot(B) return?
# B is the identity matrix
# array([[?, ?],
#        [?, ?]])

A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
A.dot(B) # returns the dot product of the two arrays, [[1, 2], [3, 4]]

array([[1, 2],
       [3, 4]])

In [17]:
# Question 5
# Given a = np.array([0, np.pi/2, np.pi]) — what does np.sin(a) return? (round to 1 dp)
# sin(0)=0
# sin(π/2)=1
# sin(π)≈0
# array([?, ?, ?])

a = np.array([0, np.pi/2, np.pi])
np.sin(a) # returns [0, 1, 0], the value of sin(x) for each number x in the array
# ignore the last one, as it is an approximation of pi and therefore not 100% precise

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [18]:
# Question 6
# Given a = np.array([10.0, 20.0, 30.0]) and b = np.array([2.0, 4.0, 5.0]) — what does np.divide(a, b) return?
# array([?, ?, ?])

a = np.array([10.0, 20.0, 30.0])
b = np.array([2.0, 4.0, 5.0])
np.divide(a, b) # returns [5, 5, 6], the results of dividing the values in a by the values in b

array([5., 5., 6.])

In [19]:
# Question 7
# Given a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) — what does np.add(a, b) return?
# array([?, ?, ?])

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.add(a, b) # returns [5, 7, 9], the result of adding the values in a with the values in b

array([5, 7, 9])

In [20]:
# Question 8
# Given a = np.array([2, 3, 4]) and b = np.array([10, 10, 10]) — what does np.multiply(a, b) return?
# array([?, ?, ?])

a = np.array([2, 3, 4])
b = np.array([10, 10, 10])
np.multiply(a, b) # returns [20, 30, 40], the result of multiplying the values in a with the values in b

array([20, 30, 40])

In [21]:
# Question 9
# Given a = np.array([0, 1, 4, 9, 16]) — what does np.sqrt(a) return?
# array([?, ?, ?, ?, ?])

a = np.array([0, 1, 4, 9, 16])
np.sqrt(a) # returns [0, 1, 2, 3, 4], or the square roots of each value in a

array([0., 1., 2., 3., 4.])