In [1]:
import numpy as np

In [23]:
################## Create ndarray from pre-maid list
first_arr = np.array([1, 2, 3])
print(first_arr)
type(first_arr) #[[1, 2, 3], [4, 5, 6]] 

[1 2 3]


numpy.ndarray

In [2]:
np.array((1, 2, 3))

array([1, 2, 3])

In [16]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
type('hi')

str

In [26]:
################## Create ndarray from range
for x in range (0, 10, 1):
    print(x, end= '  ')
print()
print(*np.arange(0, 10, 1)) # print(*) = numbers only
print(*np.arange(10)) # print(*) = numbers only
np.arange(0, 10, 1)
#create ndarray from numbers 7, 14, 21 ... to 105 [include]
print(np.arange(7, 105 +1, 7))
print(np.arange(7, 105 +1, 7)[4])

0  1  2  3  4  5  6  7  8  9  
0 1 2 3 4 5 6 7 8 9
0 1 2 3 4 5 6 7 8 9
[  7  14  21  28  35  42  49  56  63  70  77  84  91  98 105]
35


In [28]:
################## Create ndarray from zeros
print(np.zeros(5, dtype=float))
print(np.zeros(3, dtype=int))
print(np.zeros((3, 5), dtype=int))
print(*np.zeros((3, 5), dtype=int))

[0. 0. 0. 0. 0.]
[0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[0 0 0 0 0] [0 0 0 0 0] [0 0 0 0 0]


In [34]:
################## Create ndarray from range split
lin_array = np.linspace(0, 10, 3)
print(lin_array)
lin_array = np.linspace(0, 10, 4)
print(lin_array)
lin_array = np.linspace(0, 10, 4, dtype=int)
lin_array

[ 0.  5. 10.]
[ 0.          3.33333333  6.66666667 10.        ]


array([ 0,  3,  6, 10])

In [36]:
################## Create ndarray from random numbers
print(np.random.random(4)) # between 0-1
print(np.random.rand(4, 4)) # between 0-1
print(np.random.randint(0, 10 + 1, (3, 3))) # between 0-10

[0.56054668 0.04223059 0.06402653 0.71371211]
[[0.49650663 0.38249586 0.32337779 0.98077326]
 [0.08749564 0.86323301 0.85218735 0.83722003]
 [0.21696771 0.72859018 0.44409711 0.09731228]
 [0.92995554 0.2767891  0.81514701 0.1872943 ]]
[[10  3  7]
 [ 1  9  8]
 [ 7 10  4]]


In [37]:
np.array([True, False])

array([ True, False])

In [39]:
np.random.seed(42)
np.random.randint(0, 100, (2, 5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]], dtype=int32)

In [5]:
arr = np.random.randint(0, 100, size=(2, 5))
print(arr)
arr.reshape(1, 10)

[[80 67 93 92 55]
 [44 16 63 45 33]]


array([[80, 67, 93, 92, 55, 44, 16, 63, 45, 33]], dtype=int32)

In [7]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(1, 10))
print(arr)
print('max', arr.max())
print('min', arr.min())
print('arg_max index-max #', arr.argmax())
print('arg_min index-min #', arr.argmin())
print(arr.shape)

[[51 92 14 71 60 20 82 86 74 74]]
max 92
min 14
arg_max index-max # 1
arg_min index-min # 2
(1, 10)


In [15]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr)
print(arr[3])
print(arr[3::5])
print(arr[::-1])
arr[0:5] = 100
print(arr)

[51 92 14 71 60 20 82 86 74 74]
71
[71 74]
[74 74 86 82 20 60 71 14 92 51]
[100 100 100 100 100  20  82  86  74  74]


In [10]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print()
# אנדיקס ראשון יהיה לפי שורות והשני יהיה לפי המיקום של האינדקס בתוך השורה
print(arr[0],   'arr[0]')
print(arr[0][-1],   'arr[0][-1]')
print(arr[2][3],   'arr[2][3]')
print(arr[:, 0],   'arr[:, 0]')

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]

[51 92 14 71 60] arr[0]
60 arr[0][-1]
2 arr[2][3]
[51 20 87 52  1] arr[:, 0]


In [11]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
arr2 = arr  # alias, shallow copy 
arr2[0] = [1, 2, 3, 4, 5]
print('arr2 \n', arr2)
print('arr \n', arr)  # also CHANGED !! -- same as deep copy
x = 5 # 5
y = x 
y = y + 1 # 6
# next cell

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr2 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]


In [12]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
arr2 = arr.copy()  # deep copy
arr2[0] = [1, 2, 3, 4, 5]
print('arr2 \n', arr2)
print('arr \n', arr)  # not CHANGED !! -- same as deep copy

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr2 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr 
 [[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]


In [13]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(25))
print(arr)
arr > 4 # condition -> creates bool array

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True])

In [19]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5))
print(arr)
print('arr > 55 \n',arr > 55) # condition -> creates bool array
print ( [True, False, False, True, False] )
result_up_55 = arr [ [True, False, False, True, False] ]
print(result_up_55)

[51 92 14 71 60]
arr > 55 
 [False  True False  True  True]
[True, False, False, True, False]
[51 71]


In [17]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5))
print(arr)
print('arr > 55 \n', arr > 55) # condition -> creates bool array
print()
print('arr[arr > 55]', arr[arr > 55])

[51 92 14 71 60]
arr > 55 
 [False  True False  True  True]

arr[arr > 55] [92 71 60]


In [3]:
# 1 create 20 numbers between 0-100 (seed 42) and keep only even numbers
np.random.seed(42)
arr = np.random.randint(0, 100, size=(20))
print(arr)
print('arr[arr % 2 == 0]', arr[arr % 2 == 0])
print()

# 2 create 20 numbers between 0-100 (seed 42) and keep only number smllaer than 40
np.random.seed(42)
arr = np.random.randint(0, 100, size=(20))
print(arr)
print('arr[arr < 40]', arr[arr < 40])
print()

# 3 arr = np.array([10, 20, 30, 99, 40, 50, 99, 60]) keep only numbers not 99
arr = np.array([10, 20, 30, 99, 40, 50, 99, 60])
print('arr[arr != 99]', arr[arr != 99])

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
arr[arr % 2 == 0] [92 14 60 20 82 86 74 74  2 52]

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
arr[arr < 40] [14 20 23  2 21  1 29 37]

arr[arr != 99] [10 20 30 40 50 60]


In [8]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr)
print('(arr >= 55) and (arr <= 71) \n', (arr >= 55) & (arr <= 71)) # condetion -> between 51 and 71
print()
print(' (arr >= 55) and (arr <= 71)) \n', arr[(arr >= 55) & (arr <= 71)]) 
print(' (arr >= 55) or (arr <= 71)) \n', arr[(arr >= 55) | (arr <= 71)]) 

[51 92 14 71 60 20 82 86 74 74]
(arr >= 55) and (arr <= 71) 
 [False False False  True  True False False False False False]

 (arr >= 55) and (arr <= 71)) 
 [71 60]
 (arr >= 55) or (arr <= 71)) 
 [51 92 14 71 60 20 82 86 74 74]


In [12]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr, 'arr')
print("+5")
print(arr + 5, 'arr + 5')

[51 92 14 71 60 20 82 86 74 74] arr
+5
[56 97 19 76 65 25 87 91 79 79] arr + 5


In [10]:
np.random.seed(42)
arr1 = np.random.randint(0, 100, size=(10))
np.random.seed(49)
arr2 = np.random.randint(0, 100, size=(10))
print(arr1, 'arr1')
print("+")
print(arr2, 'arr2')
print("=")
print(arr1 + arr2)

[51 92 14 71 60 20 82 86 74 74] arr1
+
[42 45 40 54 12 69  5 49 18 36] arr2
=
[ 93 137  54 125  72  89  87 135  92 110]


In [9]:
np.random.seed(42)
x = np.random.randint(0, 100, size=(4))
print('x')
print(x)
y = 2 * x + 3
print('y = 2 * x + 3')
print(y)

x
[51 92 14 71]
y = 2 * x + 3
[105 187  31 145]


In [11]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print('max in matrix', arr.max())
print('max per column', arr.max(axis=0))
print('max per row', arr.max(axis=1))
print('min', arr.min())
print('arg_max index-max per column #', arr.argmax(axis=0))
print('arg_min index-min per column #', arr.argmin(axis=0))
print('sum per column', arr.sum(axis=0))
print('sum per row', arr.sum(axis=1))
print(arr.shape)

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
max in matrix 99
max per column [87 99 87 74 74]
max per row [92 86 99 87 63]
min 1
arg_max index-max per column # [2 2 3 1 1]
arg_min index-min per column # [4 3 0 2 2]
sum per column [211 337 269 196 224]
sum per row [288 336 232 206 175]
(5, 5)


In [17]:
#Create a 2-dimensional array with 5 rows and 5 columns. Populate this array with random
#integers that range from 0 to 100. Make sure your seed set to 101.
np.random.seed(101)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)    
#● Calculate the following statistics for each row:
#○ The sum of the elements
print('sum of the elements', arr.sum())

#○ The minimum value among the elements
print('min', arr.min())

#○ The maximum value among the elements
print('max', arr.max())

#○ The mean (average) of the elements
print('mean', arr.mean())

#○ The median of the elements
print('median', np.median(arr))

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]
 [64  5 12 93 40]
 [49 83  8 29 59]]
sum of the elements 1309
min 4
max 95
mean 52.36
median 60.0
