In [1]:
import numpy as np

In [2]:
# Q1
# Create exactly this 1D array:
# array([3, 14,  7, 21,  9])

np.array((3, 14,  7, 21,  9))

array([ 3, 14,  7, 21,  9])

In [3]:
# Q2
# Create a random integer array of this shape with values in [1, 10). Your values will differ!
# Example output (your values will differ):
# array([[4, 9, 2, 7, 1],
#        [8, 5, 3, 6, 4]])
# shape: (2, 5)  |  dtype: int64  |  range: [1, 10)

np.random.randint(1, 10, size=(2, 5), dtype=np.int64)

array([[8, 3, 6, 8, 5],
       [3, 9, 9, 3, 2]])

In [4]:
# Q3
# Create this array of exactly 5 evenly-spaced values:
# array([0.  , 0.25, 0.5 , 0.75, 1.  ])

lin_array = np.linspace(0, 1, 5)
lin_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# Q4
# Create this 2D matrix:
# array([[1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.]])
# # shape: (2, 5)

np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Q5
# Create a random float array of this exact shape. Your values will differ — that is expected!
# Example output (your values will differ):
# array([[0.37, 0.95, 0.73],
#        [0.60, 0.16, 0.06],
#        [0.84, 0.22, 0.48]])
#  shape: (3, 3)  |  dtype: float64  |  values in [0, 1)

np.random.rand(3,3)

array([[0.72128033, 0.47937801, 0.48677278],
       [0.22896878, 0.52881646, 0.0723804 ],
       [0.23239494, 0.12158319, 0.12801511]])

In [7]:
# Q6
# Allocate an uninitialized block of memory for a (4, 3) array — the fastest possible allocation. You will fill every cell before reading it.
# Goal: reserve uninitialized memory
# shape: (4, 3)  |  dtype: float64
# ⚡ Fastest allocation — no fill step
# ⚠  You must overwrite every cell before reading!

arr = np.empty((4, 3), dtype=np.float64)
print(arr)

[[1.60330622e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.11260619e-306 1.79253327e+160]
 [3.14180578e-032 2.05442508e+160 1.43758542e-071]
 [2.23010221e+160 2.23248577e+180 4.08673653e-033]]


In [8]:
# Q7
# Create this constant-filled 2D matrix:
# array([[9, 9, 9],
#        [9, 9, 9],
#        [9, 9, 9]])
# shape: (3, 3)  |  fill_value = 9

np.full((3, 3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [9]:
# Q8
# Create this identity matrix:
# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])
# shape: (4, 4)

np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# Q9
# Create this 2D matrix:
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])
# shape: (3, 4)

arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# Q10
# Create this evenly-spaced 1D array:
# array([  0,   5,  10,  15,  20,  25])

arr = np.arange(0, 25 +1, 5 ,dtype = int)
arr

array([ 0,  5, 10, 15, 20, 25])